### ISSUE TITLE
New bug?: a yellow "update" floating as the first line 

### ISSUE THREAD

**Issue by realliyifei** [tomy0000000/Coinc#10]
Hello again, I'm a long time user of your workflow. Since you change the name, I re-install this workflow and reset the ID and config. I figure out a "bug" but am not sure whether it's a problem in the new code or in my local setting.

There is a yellow "update" floating as the first line when typing number w/o any suffix.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/32441766/92391008-850a2880-f14e-11ea-816b-f0b6ccd2fc15.png">

**Comment by tomy0000000** [comment]
This is not a bug, but a normal behavior, you can see an identical scheenshot in [User Guide](https://github.com/tomy0000000/Coinc/wiki/User-Guide).

This row is there as an indication of what rate was used on conversion, if anyone is sensitive and expect a real-time conversion.

I do wondering, in what cases do you think this info is unnecessary/unuseful, if you might?

**Comment by yli** [comment]
Ah, it makes sense 👍 . Currency conversion is indeed time-sensitive.

I just wonder why it's different from the last version. NVM.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/32441766/92401548-79bff880-f160-11ea-87f9-9f22a4b50afa.png">

**Comment by tomy0000000** [comment]
I've looked thruogh the release history, it is added in v1.2.0. By the fact that this is an undocumented change, I guess I might have forgot to make the design decision of keeping this feature or not.

Will taking this into account for the next release, thanks for mentioning this.

**Comment by jdenormandie** [comment]
Maybe the "Last update" status could go at the bottom of the list rather than the top?

**Comment by tomy0000000** [comment]
> Maybe the "Last update" status could go at the bottom of the list rather than the top?

That's actually a reasonable suggestion, will implement

**Comment by tomy0000000** [comment]
Implemented in v2.0.0
