### ISSUE TITLE
Error in workflow 'Coinc'

### ISSUE THREAD

**Issue by jdenormandie** [tomy0000000/Coinc#13]
Hello, I have just installed Coinc 1.3.0 and have followed the set up instructions, including configuring the App_ID and fallback search but am getting an error message.  I'm on Big Sur 11.0.1 - is Coinc compatible?

Cheers,
Justin

![Screen Shot 2020-11-20 at 8 32 05 AM](https://user-images.githubusercontent.com/74761361/99772769-ace11980-2b0b-11eb-83ec-4aeabc30cd4b.png)
![Screen Shot 2020-11-20 at 8 36 30 AM](https://user-images.githubusercontent.com/74761361/99772782-b10d3700-2b0b-11eb-9b61-f7e24202bb99.png)

**Comment by tomy0000000** [comment]
I believe this is the same issue mentioned in #12, please head over there for a fix and close the issue if that's the case.

**Comment by jdenormandie** [comment]
Yes, that fixed it.  Thanks.
