### ISSUE TITLE
Not getting exchange value

### ISSUE THREAD

**Issue by jdenormandie** [tomy0000000/Coinc#14]
For some reason I am not getting the value of USD for NGN.  Exchange value for other currencies work as expected.  Also, I read in another Issue that commas were added, but they don't seem to be appearing here.  

![Screen Shot 2020-11-21 at 11 33 14 AM](https://user-images.githubusercontent.com/74761361/99875155-b80c7600-2bed-11eb-9bee-b1e634263f39.png)

**Comment by tomy0000000** [comment]
Thanks for reporting.
I've just confirmed this is a floating point rounding bug caused by python 2. Since Python 2 used by this workflow is a provided by macOS and is deprecated by PSF, I will figure out a solution shortly, stay tuned.

**Comment by tomy0000000** [comment]
@jdenormandie I've draft an update of v1.3.1, which should be good enough to fix the bug. Pleases download and test it, and close the issue if that works.

Kindly notice, you need to set precision to at least 3 point for it to calculate the correct result.

**Comment by jdenormandie** [comment]
Thanks, v1.3.1 is working after setting the precision to 3.
