### ISSUE TITLE
Not work after upgrade to macOS 12.3 beta

### ISSUE THREAD

**Issue by kamusis** [tomy0000000/Coinc#20]
In debug mode, after input "cur" in alfred, the error is as below:
```
[23:58:55.694] Coinc[Script Filter] Queuing argument '(null)'
[23:58:55.783] Coinc[Script Filter] Script with argv '(null)' finished
[23:58:55.786] ERROR: Coinc[Script Filter] Code 127: /Users/kamus/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/DF280CF6-E1C2-4C73-9803-EB25E1430C46: line 1: python: command not found
[23:59:06.519] Coinc[Script Filter] Queuing argument '(null)'
[23:59:06.597] Coinc[Script Filter] Script with argv '(null)' finished
[23:59:06.600] ERROR: Coinc[Script Filter] Code 127: /Users/kamus/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/1562FAF5-DAD3-4257-B26D-22FC57F9A506: line 1: python: command not found
```

Maybe the reason is [Apple removes Python 2.7 in macOS 12.3 beta](https://www.alfredapp.com/help/kb/python-2-monterey/), but I did ln -s python3 python, still can't let Coinc works.

```
❯ which python
/usr/local/bin/python
❯ ll /usr/local/bin/python
lrwxr-xr-x  1 root  wheel  25 Feb  7 22:19 /usr/local/bin/python -> /opt/homebrew/bin/python3
❯ python --version
Python 3.9.9
```

**Comment by tomy0000000** [comment]
Thanks for reporting this.

I'm currently on vacation now, I'll take a look whenever I'm available. If you already have ideas on fixing, you can draft a PR.

**Comment by tomy0000000** [comment]
@kamusis I just uploaded an v2 release candidate, please help test it out. If everything went well, I'll drop the pre-release tag

**Comment by kamusis** [comment]
@tomy0000000 Thank you for the fixing. First of all, all the "cur" command looks perfect now, running smoothly in python3!

but I'm not sure why you decide to check a hardcoding python3 path: /usr/local/bin/python3?
In "[V2 migration guide](https://github.com/tomy0000000/Coinc/wiki/V2-Migration-Guide)", you mentioned only support homebrew, but on my laptop, python3 is in 
```
❯ which python3
/opt/homebrew/bin/python3
```

I'm using M1 silicon Macbook Pro, I believed that the default PATH has been changed between homebrew for x86 and for ARM.

My suggestion:
change "cur" script to:
```
if command -v python3 1>/dev/null 2>&1; then
	python3 main.py convert $1
else
    echo '{
  "items": [
    {
      "title": "Manual Upgrade is required",
      "subtitle": "Hit enter to open migration Guide on GitHub",
      "valid": true,
      "arg": "open,https://github.com/tomy0000000/Coinc/wiki/V2-Migration-Guide",
      "icon": {
        "path": "hints/info.png"
      }
    }
  ]
}'
fi
```

In workflow environment variables page, add a PATH variables, you can fill both python3 default path for x86 and ARM into it.
![image](https://user-images.githubusercontent.com/1849506/154192095-afec0c0c-1e29-478c-80f8-d232f0ff728c.png)

BTW: cur-add/cur-rm/cur-arr are also leaved in python not python3.

**Comment by tomy0000000** [comment]
> I'm using M1 silicon Macbook Pro, I believed that the default PATH has been changed between homebrew for x86 and for ARM.

The reason I decided to use the fixed path is to ensure that the `python3` being used is indeed provided by homebrew. Therefore, I'm much prefer to hard code the path rather than having user to figure out how to configure.

I adapt [these] from homebrew installation script, which should be good enough to generate dynamic path. This is what I end up having:

```shell
UNAME_MACHINE="$(/usr/bin/uname -m)"
if [[ "${UNAME_MACHINE}" == "arm64" ]]
then
  HOMEBREW_PREFIX="/opt/homebrew"
else
  HOMEBREW_PREFIX="/usr/local"
fi

if command -v "$HOMEBREW_PREFIX/bin/python3" 1>/dev/null 2>&1; then
	$HOMEBREW_PREFIX/bin/python3 main.py convert $1
else
    echo '{
  "items": [
    {
      "title": "Manual Upgrade is required",
      "subtitle": "Hit enter to open migration Guide on GitHub",
      "valid": true,
      "arg": "open,https://github.com/tomy0000000/Coinc/wiki/V2-Migration-Guide",
      "icon": {
        "path": "hints/info.png"
      }
    }
  ]
}'
fi
``` 

> BTW: cur-add/cur-rm/cur-arr are also leaved in python not python3.

That's my mistake, will fix it

I've updated the pre-release, please check it again if you will. :)

**Comment by kamusis** [comment]
> UNAME_MACHINE="$(/usr/bin/uname -m)"
check the infra at first is a good method. should be no problem.

> I've updated the pre-release, please check it again if you will. :)
I tested the latest version, cur-add/cur-rm/cur-arr are not working, the error still is "python: command not found".
I modified 3 places manually, changed python to python3, now it's OK. 
![image](https://user-images.githubusercontent.com/1849506/154468644-137ce9eb-cd54-4715-aa20-e665a17a9706.png)

**Comment by tomy0000000** [comment]
> I tested the latest version, cur-add/cur-rm/cur-arr are not working, the error still is "python: command not found".
> I modified 3 places manually, changed python to python3, now it's OK.

That is my mistake again, because there is no exception or error detection mechanism built on workflow part, so I did not spot those changes not applying during my own test.

rc3 should fix this issue now :)

**Comment by kamusis** [comment]
Hi tommy, thank you again for the quick response and this amazing workflow 💯 
I'll close the issue.
