### ISSUE TITLE
Thousands separator

### ISSUE THREAD

**Issue by alwinsamson** [tomy0000000/Coinc#24]
Could you add please thousands separator for all currency. Ex: 500,678.90

**Comment by tomy0000000** [comment]
This feature is now available in v3. Please check it out and reopen if you have more thoughts.

**Comment by alwinsamson** [comment]
can you drop a link to the Alfred workflow gallery. I couldn't find it

**Comment by tomy0000000** [comment]
@alwinsamson The workflow is still under review. Please install it from the GitHub release at the moment. Sorry for the misleading docs. I'll update it.
